version: '3'
services: 
    mysqldb:
        image: mysql
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=root
    phpmyadmin:
        image: phpmyadmin
        ports: 
            - 8080:80
        environment: 
            - PMA_HOST=mysqldb
    ws_1_php:
        image: ws_1_php
        ports: 
            - 8081:8081
