version: '3'
services: 
    mysqldb:
        image: mysql
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=root
        volumes: 
            - mysql-data-store:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        ports: 
            - 8080:80
        environment: 
            - PMA_HOST=mysqldb
    ws_1:
        image: softsuavear/ws_1:1.0
        ports: 
            - 8000:8000
volumes: 
    mysql-data-store:
        driver: local
